import './globals.css'
import type { Metadata } from 'next'
import { Jura } from 'next/font/google'
import MainNavigation from './shared/MainNavigation'

const jura = Jura({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'FCOC - Fleet Carrier Services | Departure Board',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jura.className}>
        <MainNavigation />
        {children}
      </body>
    </html>
  )
}
